apiVersion: v1
kind: ConfigMap
metadata:
    name: config5
    namespace: metallb-system
data:
    config:
        address-pools:
            - name: default
              protocol: layer2
              addresses:
                - 192.168.79.61-192.168.79.71